version: '3.8'
services:
  umenbot:
    build: .
    image: umenbot:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000" # panel WWW (PANEL_PORT)
    # Jeśli potrzebujesz trwałych plików, zamontuj je tutaj
